---
title: "Speakers"
output: html_document
---
<br />

### Speakers: 

<br />

[Kayla Hale](https://lsa.umich.edu/eeb/people/graduate-students/kayla-sale-hale.html), University of Michigan (USA). 

[Ismaël Lajaaiti](https://isem-evolution.fr/en/membre/lajaaiti/), Université de Montpellier, Montpellier (France).

[Marco A.R. Mello](https://marcomellolab.wordpress.com/), University of São Paulo (Brazil). 

[Vincent Miele](https://lbbe.univ-lyon1.fr/fr/annuaires-des-membres/miele-vincent), CNRS, Lyon (France). 

[Andrew K. Ringsmuth](https://www.csh.ac.at/researcher/andrew-ringsmuth/), Wegener Center for Climate and Global Change, University of Graz (Austria); Complexity Science Hub Vienna (Austria). 

[Sergio Timoteo](https://cfe.uc.pt/profile/members/1700), University of Coimbra (Portugal). 

[Agustin Vitali](https://lifewp.bgu.ac.il/wp/pilos/?page_id=353), Ben-Gurion University of the Negev (Israel).

[Spencer Wood](https://www.outdoorrd.org/), University of Washington (USA). 

<br />

### Abstracts: 
<br />

**We need to talk about the topology of interaction networks**

Author: <span style="color: DarkCyan;"> Marco A. R. Mello </span> (University of São Paulo, Brazil)

By investigating two classical dilemmas about interactions between organisms of different species, we arrived at an integrative solution, which we presented as a new cognitive model. In this talk, I tell this story and explain what we discovered together
with our collaborators along this journey. First, we will explore together what the two dilemmas had in common. Second, we will see how this theoretical connection could be better understood through a graphical model. Third, we will find out how this
graphical model was turned into an algorithmic model able to predict the four most common network topologies observed in nature. Finally, although our cognitive model was originally designed for antagonisms in monolayer networks, after a series of
empirical tests and logical deductions it proved to apply also for mutualisms and multilayer networks. Now we are working to develop our model into a new syntactic theory. What consequences do our findings have for basic and applied Ecology?

<br />

**How do non-trophic interactions shape ecological stability?**

Authors: <span style="color: DarkCyan;"> Ismaël Lajaaiti </span> (Université de Montpellier, France), Matthieu Fontaine (Université de Montpellier, France), Jean-François Arnoldi (CNRS, France), Virginia Dominguez-Garcia (CSIC, Spain), Sonia Kéfi (CNRS, France)

In the context of global change, understanding ecosystem stability is a subject of great importance for biodiversity preservation. However, ecological stability can be measured using various metrics. This multiplicity of metrics raises the question of their interdependence, i.e.  whether they are correlated with each other or not. Previous studies addressed this point by investigating the behavior of stability metrics in trophic networks. However, in nature, species are well-known to interact in various ways other than feeding (e.g. facilitation, competition). Recent studies have shown that incorporating the diversity of interaction types in classical ecological models could resolve discrepancies between experiments and theory and drastically affect species diversity and overall biomass. However, these previous studies have mainly focused on investigating species coexistence, and, so far, very little work has been done on dynamical response to perturbations. The question of how the diversity of interactions affects the stability of ecological communities remains largely open. Here, we investigate how integrating four non-feeding interactions affects the stability of trophic communities using more than 20 different stability metrics. Specifically, we ask: how does the incorporation of non-trophic interactions in a trophic network affect stability metrics individually? Do the correlations between the stability metrics change with the incorporation of non-trophic interactions, and if yes, how? We found that these additional interactions affect the different stability metrics as well as their interdependence compared to an ecological community in which only feeding interactions are taken into account. Our results highlight the importance of incorporating the diversity of interactions into ecological theory to improve our fundamental understanding of the stability of ecological systems.

<br />

**Mutualism increases diversity, stability, and function of multiplex networks that integrate pollinators into food webs**

Authors: <span style="color: DarkCyan;"> Kayla R. S. Hale </span> (University of Michigan, USA; University of Guelph, Canada), Fernanda S. Valdovinos (University of Michigan, USA), Neo D. Martinez (Indiana University, USA)

Ecosystems are composed of complex networks of many species interacting in many ways. While ecologists have long studied food webs of feeding interactions, recent studies increasingly focus on mutualistic networks including plants that exchange food for reproductive services provided by animals such as pollinators. Here, I synthesize both types of consumer-resource interactions to study the effects of mutualism on ecosystems at the species, guild, and whole-community levels. I find that consumer-resource mechanisms underlying plant-pollinator mutualisms can increase persistence, productivity, abundance, and temporal stability of both mutualists and non-mutualists in food webs. These effects strongly increase with floral reward productivity and are qualitatively robust to variations in the prevalence of mutualism and pollinators feeding upon resources in addition to rewards. This work advances the ability of network theory to synthesize different types of interactions using common ecological mechanisms and illustrates how mutualism can enrich the diversity, stability, and function of complex ecosystems. I end with a discussion of how this theory can provide general insights for terrestrial ecosystems. 

<br />


**Exploring the multiplex metanetwork of North American bird interactions**

Authors: <span style="color: DarkCyan;"> Vincent Miele </span> (CNRS, France), Stephane Dray (CNRS, France),
Marc Ohlman (Grenoble University, France), Phoebe Zarnetske (Michigan
State University, USA)

Given the recent evidence that birds are declining in populations and
shifting their ranges in response to climate change, it is now
interesting to understand how much avian interaction networks are
similarly changing (or not) over space and time. Here we apply network
modeling of avian biodiversity and avian biotic interactions through
space and time (1997-present), based on a compiled database of nearly
10,000 bird-bird interactions for more than 500 bird species across
North America, and the publicly available North American Breeding Bird
Survey and eBird occurrence data. We will present the first multiplex
metanetwork of bird interactions, including trophic and non-trophic
interactions (e.g., negative -,- or -,0; positive +,+ or +,0; and
predator-prey -,+), collected throughout the USA. We will then
investigate the structure of this metanetwork using network science
analysis and finally connect these network patterns with bird
observations at different scales.

<br />

**Invasive species modulate the structure and stability of a multilayer mutualistic network**

Author: <span style="color: DarkCyan;"> Agustin Vitali </span> (Ben-Gurion University of the Negev, Israel)

Species interactions are the backbone of the structure and dynamics of communities. The extensive research into the link between structure and stability has been primarily theoretical and focused on monotrophic networks. Therefore, how the disruption of multitrophic interactions alters communities' response to perturbations in nature remains an open question. Here, we explored how non-native ungulates affect pollination-seed dispersal multilayer networks in Patagonia, Argentina. Ungulates disrupt a hummingbird-mistletoe-marsupial keystone interaction, which alters community composition. We calculated interlayer connectivity, modularity, and species' roles in connecting modules for intact vs. invaded networks. To link structural changes to stability, we quantified network tolerance to a single random species removal (disturbance propagation) and sequential species removal (robustness) using a stochastic coextinction model. Non-native ungulates reduced the connectivity between pollination and seed dispersal and produced fewer modules with a skewed size distribution. Moreover, species shifted their structural role, primarily from connectors to peripherals, thereby fragmenting the network by reducing the “bridges'' among modules. These structural changes altered the dynamics of cascading effects in the community, increasing disturbance propagation and reducing network robustness. Our results highlight the importance of understanding the mechanisms that alter the structure and subsequent stability of multitrophic communities in nature.

<br />


**Connecting ecological networks across dimensions: new insights and new struggles**

Author: <span style="color: DarkCyan;">Sérgio Timóteo</span> (University of Coimbra, Portugal)

The use of network approaches to the study of biotic interactions has seen a noticeable increase since its introduction into the field of ecology by mid-1980s. It helped us to understand structure and functioning of whole communities, their ability to withstand or predict responses to disturbances, and even evolutionary insights. However, networks were often looked at as separate entities. Recently, multilayer networks have been adopted as a way to bridge this gap, allowing the connect and incorporate dependencies across time, space or distinct types of interactions. This new approach to ecological networks brings however new challenges. How do we connect these different layers? What should we measure and how much? How do we standardize interactions within and between layers? I will present different approaches to distinct systems, to show how ecological multilayer networks provided us with a different understanding about community functioning and species roles. On the other hand, I will reflect on some of the struggles found in carrying out those same studies.

<br />


**Limits to sustainable scale: multilayer social-ecological network structure constrains cooperative management of common-pool resources**

Authors: Isaak Mengesha (University of Amsterdam, NL), Tuan M. Pham (University of Copenhagen, Denmark), <span style="color: DarkCyan;"> Andrew K. Ringsmuth </span> (University of Graz, Austria; Complexity Science Hub Vienna, Austria)

Sustainable management of common-pool resources (CPR) in the absence of centralised government through, for example, informal institutions, has been seen in both field work [1] and controlled experiments with games [2]. However, this work has focused on small-scale systems and the extent to which the derived principles of social- ecological resilience might also apply at larger scales is not fully understood [3]. Here we study the scaling of CPR management dynamics in a stylized multilayer social-ecological network model. We adapt a prior evolutionary game-theoretic model in which a social network of resource harvesters adaptively choose between a selfish harvesting strategy and a socially optimal strategy, the latter being a social norm enforced by peer-to-peer sanctioning [4,5]. We extend this by adding empirically informed network structure to the resource, creating a multilayer social-ecological network model with multiscale dynamics. We formulate a coarse-graining analysis to study how large-scale dynamics emerge from interconnected local patches. Results show that resource management by peer-to-peer sanctioning is limited by network topology: at large scales, norm defectors can cluster to escape sanctioning and overharvest with impunity. This provides the first formal demonstration of scaling limits to peer-to-peer CPR management. We discuss implications for real-world sustainable governance. 

<br />

**Title: TBA**

Author: <span style="color: DarkCyan;">Spencer Wood</span> (University of Washington, USA)

Abstract TBA





